input:
  resource: "input_read_json_protobuf"

buffer:
  none: {}

pipeline:
  threads: -1
  processors:
    - mapping: |
        root = this

output:
  stdout:
    codec: "lines"

logger:
  level: "WARN"
