input:
  file:
    paths: ["./*.json"]
    codec: "lines"
    max_buffer: 1000000
    delete_on_finish: false

buffer:
  none: {}

cache_resources:
  - label: "input_dedupe"
    memory:
      default_ttl: "60s"

pipeline:
  threads: -1
  processors:
    - dedupe:
        cache: "input_dedupe"
        key: ${! content().hash("xxhash64") }
        drop_on_err: true

output:
  stdout:
    codec: "lines"

logger:
  level: "WARN"
