input:
  resource: "input_read_json"

buffer:
  none: {}

pipeline:
  threads: -1
  processors:
    - group_by_value:
        value: ${! json("age") }

output:
  stdout:
    codec: "lines"

logger:
  level: "WARN"
