input:
  broker:
    inputs:
      - resource: "read_json"
      - resource: "read_json_protobuf"
      - resource: "read_json_protobuf_base64"
    batching:
      period: "1s"

buffer:
  none: {}

pipeline:
  threads: -1
  processors:
    - group_by_value:
        value: ${! json().firstName }

output:
  resource: "write_stdout"

logger:
  level: "WARN"

shutdown_delay: "1s"
