input:
  resources: "input_read_json"

buffer:
  none: {}

cache_resources:
  - label: "input_dedupe"
    memory:
      default_ttl: "60s"

pipeline:
  threads: -1
  processors:
    - dedupe:
        cache: "input_dedupe"
        key: ${! content().hash("xxhash64") }
        drop_on_err: true

output:
  stdout:
    codec: "lines"

logger:
  level: "WARN"
