input:
  resource: "read_json"

buffer:
  none: {}

pipeline:
  threads: -1
  processors:
    - mapping: |
        root.name = this.firstName + ":" + this.lastName

output:
  resource: "write_stdout"

logger:
  level: "INFO"
