input:
  resource: "input_read_json"

buffer:
  none: {}

pipeline:
  threads: -1
  processors:
    - mapping: |
        root.name = this.firstName + this.lastName

output:
  stdout:
    codec: "lines"

logger:
  level: "WARN"
