input:
  broker:
    inputs:
      - resource: "read_json"
      - resource: "read_json_protobuf"
      - resource: "read_json_protobuf_base64"

buffer:
  none: {}

pipeline:
  threads: -1
  processors:
    - mapping: |
        root.name = this.firstName + " " + this.lastName

output:
  resource: "write_stdout"

logger:
  level: "WARN"

shutdown_delay: "1s"
