input:
  resource: "read_json_batched"

buffer:
  none: {}

pipeline:
  threads: -1
  processors:
    - mapping: |
        root = this

output:
  resource: "write_stdout"

  stdout:
    codec: "lines"

logger:
  level: "INFO"
