name: Benthos Playground Test(s)

on:
  pull_request:
  push:
    branches:
    - trunk

jobs:
    test:
        name: Test all pipelines
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the all the tests using the docker image
            uses: addnab/docker-run-action@v3
            with:
                image: jeffail/benthos:latest
                options: --rm --volume /home/runner/work/benthos-playground/benthos-playground:/tmp/benthos-playground 
                run: |
                    lint /tmp/benthos-playground/resources/...
                    lint /tmp/benthos-playground/pipelines/...
                    test /tmp/benthos-playground/pipelines/...
